### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by juliangut** [notFloran/mjml-bundle#26]
It would be nice to have a validate method in the renderer? 

https://mjml.io/documentation/#in-cli

**Comment by TheRichCourt** [comment]
I need this feature too.

Couldn't find a contributing guide, so I hope you don't mind me submitting this PR https://github.com/notFloran/mjml-bundle/pull/44

Makes it possible to set the [validation level].(https://github.com/mjmlio/mjml/tree/master/packages/mjml-validator#validating-mjml)

Example config:

```yaml
mjml:
    renderer: binary
    options:
        binary: '%kernel.project_dir%/node_modules/.bin/mjml'
        minify: true
        validation_level: skip
```
